# BASE dados MGX1 rodar \i BD_1.sql

DROP DATABASE IF EXISTS projeto_bd1;
CREATE DATABASE projeto_bd1; 
USE projeto_bd1;

CREATE TABLE Vacina(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(25) NOT NULL,
	Fase VARCHAR(25) NOT NULL,
	Principio VARCHAR(25) NOT NULL
)AUTO_INCREMENT = 1;

CREATE TABLE Distribuicao(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Quantidade INTEGER NOT NULL,
	Grupo VARCHAR(25) NOT NULL,
	Data TIMESTAMP NOT NULL,
	Local VARCHAR(25) NOT NULL
)AUTO_INCREMENT = 1;


CREATE TABLE RelDistVac(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Vacina INT NOT NULL,
	Distribuicao INT NOT NULL,
	FOREIGN KEY (Vacina) REFERENCES Vacina(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Distribuicao) REFERENCES Distribuicao(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT = 1;

CREATE TABLE Acompanhamento(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Teste INT NOT NULL,
	Quantidade INTEGER NOT NULL,
	Status VARCHAR(25) NOT NULL,
	Biotipo VARCHAR(25) NOT NULL,
	Local VARCHAR(25) NOT NULL,
	FOREIGN KEY (Teste) REFERENCES Teste(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT = 1;

CREATE TABLE Pais(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(25) NOT NULL,
	Sigla VARCHAR(2) NOT NULL,
	Continente VARCHAR(25) NOT NULL
)AUTO_INCREMENT = 1;

CREATE TABLE RelTestVac(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Vacina INT NOT NULL,
	Teste INT NOT NULL,
	FOREIGN KEY (Vacina) REFERENCES Vacina(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Teste) REFERENCES Teste(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT = 1;

CREATE TABLE Teste(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Vacina INT NOT NULL,
	Pais INT NOT NULL,
	Acompanhamento INT NOT NULL,
	Quantidade INTEGER NOT NULL,
	DataInicio TIMESTAMP NOT NULL,
	DataFim TIMESTAMP NOT NULL,
	Local VARCHAR(25) NOT NULL,
	FOREIGN KEY (Vacina) REFERENCES Vacina(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Pais) REFERENCES Pais(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Acompanhamento) REFERENCES Acompanhamento(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT = 1;



CREATE TABLE Instituicao(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(25) NOT NULL,
	Local VARCHAR(25) NOT NULL,
	FOREIGN KEY (Pais) REFERENCES Pais(ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
)AUTO_INCREMENT = 1;


CREATE TABLE Game(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Inicio TIMESTAMP NOT NULL DEFAULT NOW(),
	Fim TIMESTAMP NOT NULL DEFAULT NOW(),
	Vencedor VARCHAR(25),
	FOREIGN KEY (Vencedor) REFERENCES Player(Username)
		ON DELETE SET NULL ON UPDATE CASCADE
)AUTO_INCREMENT = 1;

CREATE TABLE Relaciona(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Game INT NOT NULL,
	Player VARCHAR(25),
	Score INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (Player) REFERENCES Player(Username)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Game) REFERENCES Game(ID)
		ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT = 1;



